# Generated by Django 3.1.7 on 2021-04-10 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('specialization', models.CharField(blank=True, max_length=40)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('experience', models.CharField(blank=True, max_length=40)),
                ('level_english', models.CharField(blank=True, max_length=40)),
                ('salary', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('mode_work', models.CharField(blank=True, max_length=40)),
                ('size_team', models.CharField(blank=True, max_length=20)),
                ('size_company', models.CharField(blank=True, max_length=20)),
                ('talework', models.BooleanField(default=None)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=300, unique_for_date='publish')),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactivate', 'Inactivate')], default='active', max_length=20)),
                ('agent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_post', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Newswork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=300, unique_for_date='publish')),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactivate', 'Inactivate')], default='active', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
