# Generated by Django 3.1.7 on 2021-04-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210410_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='agent_email',
            new_name='agent',
        ),
    ]
