# Generated by Django 3.1.7 on 2021-05-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_auto_20210410_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
