# Generated by Django 3.1.7 on 2021-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20210512_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size_company',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
