# Generated by Django 3.1.7 on 2021-05-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20210513_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size_company',
            field=models.IntegerField(blank=True),
        ),
    ]
