# Generated by Django 3.1.7 on 2021-05-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210513_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=9)),
                ('description', models.TextField(blank=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=300, unique_for_date='publish')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactivate', 'Inactivate')], default='active', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_post', to='work.post')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
