# Generated by Django 3.1.7 on 2021-05-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size_company',
            field=models.IntegerField(),
        ),
    ]
